### PR TITLE
Added function input and return types to C++ library example so it will

### LINKED ISSUE #388: Compile and link statically do a bundled C++ library does not compile
[This example](https://rust-lang-nursery.github.io/rust-cookbook/build_tools.html#ex-cc-static-bundled-cpp) doesn't compile currently.

The function inputs in [`foo.cpp`](https://rust-lang-nursery.github.io/rust-cookbook/build_tools.html#srcfoocpp) aren't specified, and the return type needs to be added to the `extern` in [`main.rs`](https://rust-lang-nursery.github.io/rust-cookbook/build_tools.html#srcmainrs-1).

Right now the cpp code an error saying `x` and `y` were not declared.
```
cargo:warning=src/foo.cpp: In function ‘int multiply()’:
cargo:warning=src/foo.cpp:7:12: error: ‘x’ was not declared in this scope
cargo:warning=     return x * y;
cargo:warning=            ^
cargo:warning=src/foo.cpp:7:16: error: ‘y’ was not declared in this scope
cargo:warning=     return x * y;
cargo:warning=                ^
exit code: 1
```
The rust side fails with
```
error[E0277]: the trait bound `(): std::fmt::Display` is not satisfied
 --> src/main.rs:7:24
  |
7 |         println!("{}", multiply(5, 7));
  |                        ^^^^^^^^^^^^^^ `()` cannot be formatted with the default formatter; try using `:?` instead if you are using a format string
  |
  = help: the trait `std::fmt::Display` is not implemented for `()`
  = note: required by `std::fmt::Display::fmt`
```
as the return type is currently `()`

### PR DESCRIPTION
**Pull request by Fierthraix**
Explicitly added return types and function inputs in example.

fixes #388

### CODE REVIEW

**Comment by jrakow** [comment]
Duplicate of #385 
😃

**Comment by Fierthraix** [comment]
Sorry! I just checked the issues first without looking at the pull requests!

**Comment by Fierthraix** [comment]
Our code is identical, but yours didn't pass the tests for some reason.
Is it possible to rerun the integration tests?

**Comment by AndyGauge** [comment]
Closing as duplicate

**Pull request closed without merging**
