### PR TITLE
Fix issue #573 - hmac example

### PR DESCRIPTION
**Pull request by quaesaevum**
fixes issue #573 

Questions/concerns:
Section does not pass test under cargo test, but runs fine locally, on Rust playground, and under 'mdbook serve' on localhost.  It appears testing may refer to an older version of the ring crate.  Which version of ring does 'cargo test' call?

### CODE REVIEW

**Comment by AndyGauge** [comment]
This is great, but you want to also update the Cargo.toml file https://github.com/rust-lang-nursery/rust-cookbook/blob/master/Cargo.toml#L43
`cargo test` uses the cookbooks Cargo.toml file.

**Comment by quaesaevum** [comment]
Updated Cargo.toml as well.

**Comment by AndyGauge** [comment]
So, it looks like this breaks https://rust-lang-nursery.github.io/rust-cookbook/concurrency/threads.html#calculate-sha1-sum-of-iso-files-concurrently due to:
error[E0432]: unresolved import `ring::digest::SHA1`
  --> /tmp/rust-skeptic.WtyY3w319zV3/test.rs:13:37
   |
13 | use ring::digest::{Context, Digest, SHA1};
   |                                     ^^^^ no `SHA1` in `digest`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0432`.
test threadpool_walk_sect_calculate_sha1_sum_of_iso_files_concurrently_line_11 ... FAILED

Seems that SHA1 has been deprecated so we ought to highlight SHA-256.

Let me know if you are comfortable with that or you need me to help.

**Comment by quaesaevum** [comment]
Gave it a shot.

I'm still seeing one error, but it seems unrelated to any of my changes.

**Comment by AndyGauge** [comment]
Yeah, I have that fixed in the 2018 edition update.  I should probably separate it now that 2018 looks like a chore.

**Comment by AndyGauge** [comment]
Thank you
!

**Pull request merged**
