### PR TITLE
Fixes #570 - Updated Postgres examples

### LINKED ISSUE #570: Postgres examples are outdated
The crate name and version button both link to https://docs.rs/postgres/0.15.2/postgres/ even though the button says `v0.17.0`. More importantly, the later version has renamed the `Connection` struct as `Client`. Also, `TlsMode::None` needs to be replaced by `NoTls`.

### PR DESCRIPTION
**Pull request by Gabighz**
Fixes #570 

Updated links to reference latest postgres docs. Replaced `Connection` struct with `Client`. Replaced `TlsMode::None` with `NoTls`.

### CODE REVIEW

**Comment by AndyGauge** [comment]
In order to upgrade the version of Postgres with the test suite, I'd ask that you update the Cargo.toml file as well.
https://github.com/rust-lang-nursery/rust-cookbook/blob/master/Cargo.toml#L38

Thank you for the PR!

**Comment by Gabighz** [comment]
Oh yeah, sorry about that. I updated the manifest file with the latest postgres crate, but I have a test that fails.

`test insert_select_sect_insert_and_select_data_line_8 ... FAILED`

Honestly, I'm not sure what the failing code is. I had a feeling that it's maybe the `insert_query_data.md` file. But I just ran all the code that I edited for this pull request in a separate package on my machine with only postgres as a dependency and the code executed as intended. 

Should I commit as it is?

**Comment by AndyGauge** [comment]
Its not you its me.  We've fixed that in a PR that will likely drag on, do you want to backport it?  Here's the fix:
https://github.com/rust-lang-nursery/rust-cookbook/pull/565/commits/7a5d17a7d639a2cb1e5a8b76c61fb7fdffb0ce74

**Comment by Gabighz** [comment]
Thank you for the link! I've rerun the tests and made sure that cargo did indeed download rusqlite v0.21, but the test still fails.

However, if it's not related to the PR, it's no worries. If you wish, we could merge this branch for the postgres examples. 

And, at a later date, I could take a look at `insert_data.md` from the sqlite examples and see why the test fails. I'm assuming that's where it fails.

**Pull request merged**
