### PR TITLE
Reorganise science and fix broken links

### LINKED ISSUE #472: Science links broken
In fact every link in Science is currently broken 😟
They link to e.g. https://rust-lang-nursery.github.io/rust-cookbook/science/mathematics/complex-numbers.html, which don't seem to exist.

### PR DESCRIPTION
**Pull request by JamesHinshelwood**
fixes #472 

We should formalise how to lay things out to avoid this in the future and conventions. e.g. `_`s and `-`s, where to put tables, etc.

This format does involve a fair bit of (error prone) duplication from writers - maybe in the future this could be automaed?

Here is a rough diagram I drew up
```
section.md - Contains {{#include section/category.md}} for large categories and tables for small_subcategories
section
├──category.md - Contains tables for each subcategory
├──category - Contains multiple subcategories
│   ├──subcategory.md - Contains {{#include subcategory/recipe.md}}s
│   └──subcategory
│       └──recipe.md - Contains actual recipe
│
├──small_subcategory.md - Contains {{#include small_subcategory/recipe.md}}
└──small_subcategory - Should be preferred when an extra level of nesting is unnecessary
    └──recipe.md - Contains actual recipe
```

### CODE REVIEW

**Comment by AndyGauge** [comment]
I'm not available to attempt this, but originally Math was not supposed to have sub-series.  I should have time tomorrow to look at this rendered to see if I agree with the direction.

**Comment by JamesHinshelwood** [comment]
I was following the example of `development_tools/debugging` and `web_programming/clients`, especially since `mathematics` is quite a large field :stuck_out_tongue: 

The alternative, if we follow the current convention, would be to have all mathematics recipes listed in `science/mathematics.html`, as in `development_tools/versioning`. It might be confusing to have everything from matrices to complex numbers all in one long page.

**Comment by AndyGauge** [comment]
I forgot to review this today.  My bad.  Thank you for the effort, but it may be a few days before I respond.

**Comment by JamesHinshelwood** [comment]
No problem. I will wait with fixing the conflicts till we are happy with this structure. It won't take long just need to move some stuff from #466 .

**Comment by AndyGauge** [comment]
Sure lets do this, but make Complex Numbers 17.3 instead of 17.1

**Comment by JamesHinshelwood** [comment]
@AndyGauge Sure, I'll do it right now, thanks

**Comment by JamesHinshelwood** [comment]
@AndyGauge 
So, you want

```
17.1.1 Linear Algebra
17.1.2 Trigonometry
17.1.3 Complex Numbers

```
?

**Comment by AndyGauge** [comment]
Yes.

**Comment by JamesHinshelwood** [comment]
@AndyGauge Done

**Pull request merged**
