### PR TITLE
Old Code Would Not Compile

### PR DESCRIPTION
**Pull request by vthg2themax**
I researched the Chrono library and made sure the code would compile with the latest Rust 2018 setup.

fixes #ISSUE_ID

:tada: Hi and welcome! Please read the text below and remove it - Thank you! :tada:

No worries if anything in these lists is unclear. Just submit the PR and ask away! :+1:

--------------------------
### Things to check before submitting a PR

- [ ] the tests are passing locally with `cargo test`
- [ ] cookbook renders correctly in `mdbook serve -o`
- [ ] commits are squashed into one and rebased to latest master
- [ ] PR contains correct "fixes #ISSUE_ID" clause to autoclose the issue on PR merge
    -  if issue does not exist consider creating it or remove the clause
- [ ] spell check runs without errors `./ci/spellchecker.sh`
- [ ] link check runs without errors `link-checker ./book`
- [ ] non rendered items are in sorted order (links, reference, identifiers, Cargo.toml)
- [ ] links to docs.rs have wildcard version `https://docs.rs/tar/*/tar/struct.Entry.html`
- [ ] example has standard [error handling](https://rust-lang-nursery.github.io/rust-cookbook/about.html#a-note-about-error-handling)
- [ ] code identifiers in description are in hyperlinked backticks
```markdown
[`Entry::unpack`]: https://docs.rs/tar/*/tar/struct.Entry.html#method.unpack
```

### Things to do after submitting PR
- [ ] check if CI is happy with your PR

Thank you for reading, you may now delete this text! Thank you! :smile:

### CODE REVIEW

**Comment by AndyGauge** [comment]
I'd be happy having a recipe that shows the colors relationship without any date information and then a separate recipe that shows how chrono works with SQLite.  Would you be up for that?

**Comment by vthg2themax** [comment]
Yeah, I can probably do that. Chronos feels really difficult to get used to coming from a VB.NET background, and adding too many new things at once is mentally exhausting. Did you pull the Chronos parts out of my commit, or do I need to do something here to make the suggested change?

**Comment by AndyGauge** [comment]
I haven't touched your branch or the PR.  You are free to experiment with either direction and I can help if you get stuck.

**Comment by vthg2themax** [comment]
I removed Chrono, and simplified the code. How's that? I am still new to GitHub, so feel free to let me know if I've missed something.

**Comment by AndyGauge** [comment]
Looks good to me,

**Pull request merged**
