### PR TITLE
update rand-dist

### PR DESCRIPTION
**Pull request by TianyiShi2001**
This PR addresses issue #580 

- [ ] the tests are passing locally with `cargo test` **see below**
- [X] cookbook renders correctly in `mdbook serve -o`
- [X] commits are squashed into one and rebased to latest master
- [X] PR contains correct "fixes #ISSUE_ID" clause to autoclose the issue on PR merge
    -  if issue does not exist consider creating it or remove the clause
- [X] spell check runs without errors `./ci/spellcheck.sh`
- [ ] link check runs without errors `link-checker ./book` **command not found (MacOS; tried brew and cargo install)**
- [X] non rendered items are in sorted order (links, reference, identifiers, Cargo.toml)
- [X] links to docs.rs have wildcard version `https://docs.rs/tar/*/tar/struct.Entry.html`
- [ ] example has standard [error handling](https://rust-lang-nursery.github.io/rust-cookbook/about.html#a-note-about-error-handling)
- [X] code identifiers in description are in hyperlinked backticks
```markdown
[`Entry::unpack`]: https://docs.rs/tar/*/tar/struct.Entry.html#method.unpack
```

### Things to do after submitting PR
- [ ] check if CI is happy with your PR

Thank you for reading, you may now delete this text! Thank you! :smile:

### CODE REVIEW

**Comment by TianyiShi2001** [comment]
I'm unsure about error handling. If I write

```rust
#[macro_use]
extern crate error_chain;
extern crate rand_distr;
use rand_distr::{Distribution, Normal};

error_chain! {
    foreign_links {
        NormalDistribution(rand_distr::NormalError);
    }
}

fn main() -> Result<()> {
    let mut rng = rand::thread_rng();
    let normal = Normal::new(2.0, 3.0)?;
    let v = normal.sample(&mut rng);
    println!("{} is from a N(2, 9) distribution", v);
    Ok(())
}
```

The compiler says: 

```
error[E0277]: `rand_distr::NormalError` doesn't implement `std::fmt::Display`
```

Therefore I used `Result<(), rand_distr::NormalError>` instead.

**Comment by JOE1994** [comment]
Hello, I cloned your fork locally and tried `cargo test`, but I'm somehow not seeing the same error you mentioned here. Could you try running `cargo clean` and then `cargo test` again?

p.s. I pushed a small commit that fixes test `insert_select_sect_insert_and_select_data_line_8`.

**Comment by JOE1994** [comment]
FYI, I pushed a fix to master for `insert_select_sect_insert_and_select_data_line_8`, and the error for the test is gone now.

**Comment by JOE1994** [comment]
I forked your branch, and tried running `cargo test`, but couldn't reproduce the same error message..
Could you try running `cargo clean` locally and then run `cargo test` again?

**Comment by TianyiShi2001** [comment]
I `cargo clean`ed and `cargo test`ed again, only to get the same error. My `rustc` and `cargo` version is `1.42.0`.

Below is the complete error log:

```
Running `/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/skeptic-2506cd4c0dab09a4 rand_dist_sect_generate_random_numbers_with_given_distribution_line_15`

running 1 test
error[E0277]: the trait bound `rand::ThreadRng: rand_core::RngCore` is not satisfied
  --> /var/folders/gh/mmj3zq61685f8l61193mrybr0000gn/T/rust-skeptic.VTo4TK60oEv2/test.rs:10:27
   |
10 |     let v = normal.sample(&mut rng);
   |                           ^^^^^^^^ the trait `rand_core::RngCore` is not implemented for `rand::ThreadRng`
   |
   = note: required because of the requirements on the impl of `rand::Rng` for `rand::ThreadRng`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
test rand_dist_sect_generate_random_numbers_with_given_distribution_line_15 ... FAILED

failures:

---- rand_dist_sect_generate_random_numbers_with_given_distribution_line_15 stdout ----
thread 'rand_dist_sect_generate_random_numbers_with_given_distribution_line_15' panicked at 'Command failed:
"rustc" "/var/folders/gh/mmj3zq61685f8l61193mrybr0000gn/T/rust-skeptic.VTo4TK60oEv2/test.rs" "--verbose" "--crate-type=bin" "-L" "/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug" "-L" "/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps" "--target" "x86_64-apple-darwin" "--extern" "ring=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libring-bf23530c746c14b5.rlib" "--extern" "num_cpus=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libnum_cpus-2beef78160e1e846.rlib" "--extern" "chrono=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libchrono-85d3b01ee2f7b297.rlib" "--extern" "byteorder=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libbyteorder-9d9e026717bb14e4.rlib" "--extern" "rand=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/librand-0079c96b7aa21a2d.rlib" "--extern" "crossbeam_channel=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libcrossbeam_channel-4085a224510023c1.rlib" "--extern" "tar=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libtar-b2f8c6bd3e2b0ec7.rlib" "--extern" "flate2=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libflate2-cf7bee8cb325ddab.rlib" "--extern" "serde_derive=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libserde_derive-fd140de320c2e127.dylib" "--extern" "crossbeam=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libcrossbeam-07be7c04d6564b96.rlib" "--extern" "rayon=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/librayon-4e6e7d13220a57e7.rlib" "--extern" "clap=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libclap-b09f2991109704b2.rlib" "--extern" "walkdir=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libwalkdir-502ceb34c53fba15.rlib" "--extern" "ndarray=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libndarray-06234ee938f3a6f1.rlib" "--extern" "ansi_term=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libansi_term-5fef1ab3ab6b81ee.rlib" "--extern" "postgres=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libpostgres-a78e333b483d55e0.rlib" "--extern" "bitflags=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libbitflags-0319435216ac8571.rlib" "--extern" "nalgebra=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libnalgebra-12eeb07a0fd6d339.rlib" "--extern" "log=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/liblog-0c0bb4c30581a943.rlib" "--extern" "cc=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libcc-52687aff05fbd90a.rlib" "--extern" "semver=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libsemver-98cf75b103f2a320.rlib" "--extern" "same_file=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libsame_file-f133ed4e4a58cec9.rlib" "--extern" "select=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libselect-251fb34b09d8018f.rlib" "--extern" "regex=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libregex-bdb467fcedf2e867.rlib" "--extern" "tempfile=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libtempfile-c4bf1da3f5d2d84a.rlib" "--extern" "env_logger=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libenv_logger-abf7e3bb13dcd6c6.rlib" "--extern" "csv=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libcsv-3c87e02dfff7afe5.rlib" "--extern" "reqwest=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libreqwest-7dbeee21e44fc538.rlib" "--extern" "unicode_segmentation=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libunicode_segmentation-e1a8101cfc68a6ca.rlib" "--extern" "serde=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libserde-a9533e5431c72087.rlib" "--extern" "image=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libimage-42784e0dcefba505.rlib" "--extern" "num=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libnum-184587773a048229.rlib" "--extern" "glob=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libglob-e93177aa1a5b28e1.rlib" "--extern" "data_encoding=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libdata_encoding-17c540508f55ad97.rlib" "--extern" "serde_json=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libserde_json-323cb24107e52681.rlib" "--extern" "base64=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libbase64-363a270843e32ad6.rlib" "--extern" "lazy_static=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/liblazy_static-8c46213ba833ecee.rlib" "--extern" "url=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/liburl-7eb5f61afa3a56d4.rlib" "--extern" "petgraph=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libpetgraph-e4455cc193cb6d65.rlib" "--extern" "memmap=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libmemmap-a7b146734ea6bfff.rlib" "--extern" "toml=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libtoml-de1d3302816dea29.rlib" "--extern" "error_chain=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/liberror_chain-b8ada8ecb5de7e3f.rlib" "--extern" "threadpool=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libthreadpool-a60ce185d2664423.rlib" "--extern" "log4rs=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/liblog4rs-9d99e0c712508d68.rlib" "--extern" "rusqlite=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/librusqlite-0c961d451e167314.rlib" "--extern" "percent_encoding=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libpercent_encoding-13483d8c48952fb7.rlib" "--extern" "skeptic=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libskeptic-bfa9311b25e9460e.rlib" "--extern" "mime=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/libmime-46802d3d6ddf9dce.rlib" "--extern" "rand_distr=/Users/tianyishi/Documents/GitHub/rust-cookbook/target/debug/deps/librand_distr-b975a0115b1adb45.rlib" "-o" "/var/folders/gh/mmj3zq61685f8l61193mrybr0000gn/T/rust-skeptic.VTo4TK60oEv2/out.exe"', /Users/tianyishi/.cargo/registry/src/github.com-1ecc6299db9ec823/skeptic-0.13.4/lib.rs:855:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by JOE1994** [comment]
Thanks for the clarification :) I was able to reproduce the error in my Linux machine (I had previously tested in my Windows machine).

I see this code snippet works well on its own in a separate project, but fails in the test process.
If you look at `Cargo.lock` after running `cargo test`, you could see that there are 5 different versions of the `rand` crate installed due to different dependencies from other imported crates. 
(Below image to show that multiple versions of `rand` are downloaded)
```
/// Part of Cargo.lock

[[package]]
name = "rand"
version = "0.3.23"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "64ac302d8f83c0c1974bf758f6b041c6c8ada916fbb44a609158ca8b064cc76c"
dependencies = [
 "libc",
 "rand 0.4.6",
]

[[package]]
name = "rand"
version = "0.4.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "552840b97013b1a26992c11eac34bdd778e464601a4c2054b5f0bff7c6761293"
dependencies = [
 "fuchsia-cprng",
 "libc",
 "rand_core 0.3.1",
 "rdrand",
 "winapi 0.3.8",
]

[[package]]
name = "rand"
version = "0.5.6"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "c618c47cd3ebd209790115ab837de41425723956ad3ce2e6a7f09890947cacb9"
dependencies = [
 "cloudabi",
 "fuchsia-cprng",
 "libc",
 "rand_core 0.3.1",
 "winapi 0.3.8",
]

[[package]]
name = "rand"
version = "0.6.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "6d71dacdc3c88c1fde3885a3be3fbab9f35724e6ce99467f7d9c5026132184ca"
dependencies = [
 "autocfg 0.1.7",
 "libc",
 "rand_chacha 0.1.1",
 "rand_core 0.4.2",
 "rand_hc 0.1.0",
 "rand_isaac",
 "rand_jitter",
 "rand_os",
 "rand_pcg",
 "rand_xorshift",
 "winapi 0.3.8",
]

[[package]]
name = "rand"
version = "0.7.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "6a6b1679d49b24bbfe0c803429aa1874472f50d9b363131f0e89fc356b544d03"
dependencies = [
 "getrandom",
 "libc",
 "rand_chacha 0.2.2",
 "rand_core 0.5.1",
 "rand_hc 0.2.0",
]
```

Cargo is somehow failing to provide the correct version(0.7) of `rand` for the code snippet.

I'm not yet sure whether this should be an issue for `Cargo` or for the `rand` crate.

**Comment by AndyGauge** [comment]
#542 all over again.  If you want to look at a minimum reproduction of the bug https://github.com/AndyGauge/Skeptic-issue-111  It looks like the way rust skeptic pulls in rlibs was the same as cargo up until rust 1.38

**Pull request merged**
