### PR TITLE
Update to edition 2018

### LINKED ISSUE #530: Update examples to 2018 edition

### LINKED ISSUE #569: type annotations needed
error[E0282]: type annotations needed for `rusqlite::MappedRows<'_, [closure@/tmp/rust-skeptic.W3uKvyKglSl5/test.rs:41:42: 46:6]>`

  --> /tmp/rust-skeptic.W3uKvyKglSl5/test.rs:42:9

   |

41 |     let cats = stmt.query_map(NO_PARAMS, |row| {

   |         ---- consider giving `cats` the explicit type `rusqlite::MappedRows<'_, [closure@/tmp/rust-skeptic.W3uKvyKglSl5/test.rs:41:42: 46:6]>`, where the type parameter `E` is specified

42 |         Ok(Cat {

   |         ^^ cannot infer type for `E`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0282`.

test insert_select_sect_insert_and_select_data_line_8 ... FAILED

### PR DESCRIPTION
**Pull request by pickfire**
Update mdbook to 0.3.5

Command:
`sed -i '/extern crate/ {N;s/\n$//}' src/**.md; sed -i 's/extern crate error_chain;/use error_chain::error_chain;/; s/extern crate lazy_static;/use lazy_static::lazy_static;/; s/extern crate bitflags;/use bitflags::bitflags;/; s/extern crate serde_json;/ use serde_json::json;/; s/extern crate serde_derive;/use serde::{Serialize, Deserialize};/; /macro_use/d; /extern crate/ d; s/```rust/```rust,edition2018/; s/bail!/error_chain::&/; s/\(debug\|info\|warn\|error\)!/log::&/;' src/**.md`

Fixes #530
Fixes #569

### CODE REVIEW

**Comment by pickfire** [comment]
@AndyGauge Interested to review?

**Comment by AndyGauge** [comment]
Yeah, I was reading it and I'm impressed.  One thing I'm concerned about is if there are any `extern crate` definitions that the text doesn't include a reference.  One thing nice about having those extern crate statements is it makes it easy to set up the recipe's Cargo.toml.  I'll build it locally and peruse.

**Comment by AndyGauge** [comment]
duh, there's crate badges right above the recipes.  That should be instructive enough.  I've peeked at it and from 30000 ft it looks good.

**Comment by pickfire** [comment]
@AndyGauge I think the notable changes are `index.hbs`, the google analytics were removed I guess. Not sure if we need it?

**Comment by pickfire** [comment]
@AndyGauge What should I do next for this?

**Comment by AndyGauge** [comment]
I'm going to try and get it compiled and uploaded to review it in book format next.

**Comment by AndyGauge** [comment]
OK, I've published it here http://www.yetanother.site/rust-cookbook/ and am reviewing

**Comment by AndyGauge** [comment]
OK, so I'm now seeing new errors... it looks like error-chain does not like its result type being ignored.  

error[E0107]: wrong number of type arguments: expected 2, found 1
  --> /tmp/rust-skeptic.HOf7zmrK9Y0r/test.rs:12:14
   |
12 | fn main() -> Result<()> {
   |              ^^^^^^^^^^ expected 2 type arguments
error: aborting due to 2 previous errors
For more information about this error, try `rustc --explain E0107`.
test about_sect_a_note_about_error_handling_line_150 ... FAILED
error: cannot find macro `error_chain_processing` in this scope
  --> /tmp/rust-skeptic.qfSON6UfVh6g/test.rs:6:1
   |
6  | / error_chain! {
7  | |     foreign_links {
8  | |         Utf8(std::str::Utf8Error);
9  | |         AddrParse(std::net::AddrParseError);
10 | |     }
11 | | }
   | |_^

**Comment by AndyGauge** [comment]
looks like we need to do this https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html
use error-chain::Result

**Comment by AndyGauge** [comment]
In order to make Travis useful, I had to fix #569 to figure out what errors are caused by this change.

**Comment by AndyGauge** [comment]
OK, here's the problem.  `error-chain` never was updated for Rust 2018 🤕 .  Now I can do that, but it looks like here https://github.com/rust-lang/rust/issues/57013 the way to fix error-chain for now is to `use` all of the internal macros.  

```
use error_chain::{error_chain, error_chain_processing, impl_error_chain_kind, impl_error_chain_processed, impl_extract_backtrace, ChainedError};
```

**Comment by AndyGauge** [comment]
It is really hard to come up with consensus on error handling.  I'm biased, because I maintain error-chain (picked up both projects after Brian left Mozilla).  I think I would use `thiserror` in my own library at this point though.  Feel free to address error-handling in #502 or #370 
The primary reason we don't switch crates is there is no ecosystem stability right now.  The cookbook is all about curated, stable libraries that the library team originally approved.  Adding crates to the list should be a hard thing.  In fact if you want to showcase `anyhow` as a recipe I'd probably approve it, and throw a `thiserror` in there too, but for blanket switching all recipes I think that would give me an aneurysm.

**Comment by pickfire** [comment]
@AndyGauge What do we need to do for this pull request?

**Comment by AndyGauge** [comment]
We've discovered a major pain point using `error-chain` with 2018.  Either we need to use the internal macros, fix error-chain, or change the error handling library.  I believe I wrote those in order of complexity.

I doubt I will be working on this error-chain change immediately, but I think that would be a good solution.  If you would rather rewrite the error handling story of the cookbook let me know if you have that capacity.

**Comment by AndyGauge** [comment]
Interestingly I discovered that error-chain 0.12 included the 2018 fix.  cargo downloads both error-chain 0.11 and 0.12, and incorrectly was using the 0.11 version.  

I feel like this is a skeptic problem.

I just recompiled this branch with rustc 1.45-nightly and had every single test fail.

**Comment by AndyGauge** [comment]
OK, let's party like its 2018!

**Comment by pickfire** [comment]
> I doubt I will be working on this error-chain change immediately, but I think that would be a good solution. If you would rather rewrite the error handling story of the cookbook let me know if you have that capacity.

Yes, I could rewrite the rust error handling story to use anyhow or thiserror.

Also, I would like change the global data story to use once_cell.

But I may not have time recently but should have some time to work this out in few weeks.

**Comment by AndyGauge** [comment]
Turns out error chain was updated and the problem was with the dependency
graph. At this time we shouldnt rewrite the error handling. Thanks!

**Comment by pickfire** [comment]
How about lazy_static? once_cell looks like a better alternative without using macro. https://docs.rs/once_cell/1.4.0/once_cell/#faq

**Comment by AndyGauge** [comment]
Funny story.  @matklad was helping me with a pre-rfc when once_cell was born.  https://internals.rust-lang.org/t/pre-rfc-lazy-static-move-to-std/7993/36 <https://internals.rust-lang.org/t/pre-rfc-lazy-static-move-to-std/7993/36>

I’m fine with a recipe on it.  How about highlighting the regex use case?  I know @burtsushi describes that as a big part of using either of these, and creating a regex is a good introductory problem.  Like https://docs.rs/once_cell/1.4.0/once_cell/#building-block <https://docs.rs/once_cell/1.4.0/once_cell/#building-block> without creating a macro?

Andrew

**Comment by pickfire** [comment]
> I’m fine with a recipe on it.  How about highlighting the regex use case?  I know @burtsushi describes that as a big part of using either of these, and creating a regex is a good introductory problem.  Like https://docs.rs/once_cell/1.4.0/once_cell/#building-block <https://docs.rs/once_cell/1.4.0/once_cell/#building-block> without creating a macro?

https://docs.rs/once_cell/1.4.0/once_cell/#building-block is creating a macro itself and regex already uses `lazy_static`, we would have to replace it with `once_cell` and can also explain the benefits of using `once_cell` such that one could do lazy initialization without macro.

**Pull request merged**
