### PR TITLE
run() -> main()

### LINKED ISSUE #433: Replace quick_main with main returning Result
Rust 1.26 allows return types on main.  This should be taught in the cookbook, rather than relying on quick_main.  

TODO: 

- [ ] Replace functions in recipes that leverage a function returning a Result and quick-main macros
- [ ] Document in a note about error handling

https://www.reddit.com/r/rust/comments/8xubdr/rust_cookbook_is_now_reorganized/e28efj7/

### PR DESCRIPTION
**Pull request by workingjubilee**
Duplicates #441 due to that PR being dead. Fixes #433.
I rebased sepiropht's work into this branch rather than reimplement it myself, and made my own changes to implement the remaining fixes as a separate commit. For this reason, there are two commits in my PR, defying the usual convention for rust-cookbook. It seemed worthwhile to open a new PR including their work since their update is very important for this repo being current and useful.

I did not address gratuitous error-chain usage because that seems like a separate concern. I left a few cases where run() was not being used as an entry point but rather a local function untouched, because it is syntactically valid, even if it is awkward and somewhat dated in style: they can be fixed later.

### Checked Before PR Opened:
- [X] the tests are passing locally with `cargo test`
- [X] cookbook renders correctly in `mdbook serve -o`
- [X] commits are squashed into **two** and rebased to latest master
- [X] PR contains correct "fixes #ISSUE_ID" clause to autoclose the issue on PR merge
- [X] spell check runs without errors `./ci/spellchecker.sh`
- [X] link check runs without errors `link-checker ./book` **ish**
- [X] non rendered items are in sorted order (links, reference, identifiers, Cargo.toml)
- [X] links to docs.rs have wildcard version `https://docs.rs/tar/*/tar/struct.Entry.html`
- [X] example has standard [error handling](https://rust-lang-nursery.github.io/rust-cookbook/about.html#a-note-about-error-handling)
- [X] code identifiers in description are in hyperlinked backticks
```markdown
[`Entry::unpack`]: https://docs.rs/tar/*/tar/struct.Entry.html#method.unpack
```

### To Check After PR Opens:
- [x] check if CI is happy with your PR

### CODE REVIEW

**Comment by AndyGauge** [comment]
Glad you addressed it, having this old way of doing things in a reference that helps newcomers is a bad idea.  I'm going to try to fix the build failure in master and then look to merge this.

**Comment by workingjubilee** [comment]
Both of the issues are on nightly. I believe my other PR fixes the sole failure on the Mac build, and that of the Xenial issues, only one is maybe introduced by this PR. They all seem to deal with the rand crate.

**Comment by AndyGauge** [comment]
#542 
I think rust skeptic is using rand 0.4 which doesn't have `rand::distributions::Distribution` when compiled on nightly.  I can reproduce it locally, and I'm seeing in `cargo tree` the only place rand doesn't have Distribution is < 0.5

**Comment by AndyGauge** [comment]
That didn't fix it.  There is something really strange going on here.

**Comment by workingjubilee** [comment]
I started experimenting a little with things here.

**Comment by AndyGauge** [comment]
> That didn't fix it. There is something really strange going on here.
I was able to fork rust-skeptic and replace the tempdir with tempfile, so there is no rand < .5 references, did a cargo clean and cargo build and cargo test and still get the behavior.

**Comment by AndyGauge** [comment]
Taking postgres out of the cargo.toml file fixes the error lol

**Comment by workingjubilee** [comment]
Ah, I'll revert my last few commits then.

**Comment by AndyGauge** [comment]
I'm working on a pr that removes tempdir as well because I think they both need to be nixed.

Thank you so much for looking into this!

**Comment by AndyGauge** [comment]
Do you want to resolve the merge conflict in src/web/clients/download/basic.md ?

**Comment by workingjubilee** [comment]
Just did.

**Comment by AndyGauge** [comment]
Aaaand I broke master.  I'm going to merge this and will work on the failures later today.

**Comment by workingjubilee** [comment]
RIP

**Comment by workingjubilee** [comment]
R I P master

**Pull request merged**
